#!/bin/sh
set -e
# Automatically added by dh_dkms/3.2.2-1
DKMS_NAME=sky1-npu
DKMS_VERSION=1.0.0

case "$1" in
    remove|upgrade|deconfigure)
      if [  "$(dkms status -m $DKMS_NAME -v $DKMS_VERSION)" ]; then
         dkms remove -m $DKMS_NAME -v $DKMS_VERSION --all
      fi
    ;;
esac
# End automatically added section
